# Generated by Django 5.0.2 on 2024-03-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_created_date_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(default='SOME STRING', verbose_name='Дата производства продукта'),
        ),
    ]
